# Generated by Django 5.1.7 on 2025-04-06 14:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_start_date_order_date_ordered_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='Shippingdetails',
        ),
    ]
