# Generated by Django 5.1.7 on 2025-04-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderitem_data_added_alter_orderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='digital',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
