# Generated by Django 5.1.7 on 2025-04-19 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_order_user_remove_shippingdetails_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
    ]
