# Generated by Django 5.1.7 on 2025-07-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_category_item_description_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='on_sale',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
